"""修改数据库名

Revision ID: e199feaea3e4
Revises: 7beceaddfe2d
Create Date: 2020-09-26 17:47:45.096384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e199feaea3e4'
down_revision = '7beceaddfe2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spiders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('publish_time', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=20), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('third_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_link', sa.String(length=255), nullable=True),
    sa.Column('short_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('iehou')
    op.drop_table('uri_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uri_link',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('real_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('short_link', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('iehou',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('publish_time', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('group', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_activated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('third_links')
    op.drop_table('spiders')
    # ### end Alembic commands ###
