"""添加权限字段

Revision ID: 027fcdee052e
Revises: 20397d9da379
Create Date: 2020-03-08 17:11:16.963875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '027fcdee052e'
down_revision = '20397d9da379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permission', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permission')
    # ### end Alembic commands ###
