"""添加字段

Revision ID: 1b356714766a
Revises: d1f01ef773a5
Create Date: 2020-03-06 15:17:44.792562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b356714766a'
down_revision = 'd1f01ef773a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iehou', sa.Column('is_activated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('iehou', 'is_activated')
    # ### end Alembic commands ###
