"""fix model

Revision ID: d1f01ef773a5
Revises: dbd85599a42f
Create Date: 2020-03-06 10:34:00.404872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1f01ef773a5'
down_revision = 'dbd85599a42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('iehou', sa.Column('group', sa.String(length=20), nullable=True))
    op.drop_column('iehou', 'origin')
    op.add_column('weibo', sa.Column('group', sa.String(length=20), nullable=True))
    op.drop_column('weibo', 'origin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weibo', sa.Column('origin', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('weibo', 'group')
    op.add_column('iehou', sa.Column('origin', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('iehou', 'group')
    # ### end Alembic commands ###
