"""add url_link table

Revision ID: f074add7e034
Revises: 1b356714766a
Create Date: 2020-03-07 18:34:04.973718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f074add7e034'
down_revision = '1b356714766a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uri_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('real_link', sa.String(length=255), nullable=True),
    sa.Column('short_link', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uri_link')
    # ### end Alembic commands ###
