from app.core.config import settings

BROKER_URL = settings.BROKER_URL
CELERY_RESULT_BACKEND = settings.CELERY_RESULT_BACKEND

CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = "Asia/Shanghai"
CELERY_ENABLE_UTC = True

